package Mongoose.WinStudio.Enums;

public enum FormEventHandlerResponseType {
  OLE(0L),
  DLL(1L),
  EXE(2L),
  CALL_FORM(3L),
  GOTO_FORM(4L),
  GOTO_FORMPAGE(5L),
  RUN_FORM_LINKED_CHILD(6L),
  RUN_FORM(7L),
  RUN_INTERNAL_SCRIPT(8L),
  SUBCOLLECTION_NAVIGATE(9L),
  SUBCOLLECTION_NEW(10L),
  SUBCOLLECTION_SAVE(11L),
  SUBCOLLECTION_DELETE(12L),
  SUBCOLLECTION_REFRESH(13L),
  SUBCOLLECTION_COPY(14L),
  SUBCOLLECTION_REFRESH_CURRENT(15L),
  CALL_FORM_FOR_FILTER(16L),
  SUBCOLLECTION_NOTES(17L),
  SUBCOLLECTION_CUR_NOTES(18L),
  RUN_BACKGROUND_TASK(19L),
  TIMER(20L),
  GENERATE_EVENT(21L),
  SET_VALUES(22L),
  COLLECTION_NAVIGATE(23L),
  COLLECTION_NEW(24L),
  COLLECTION_COPY(25L),
  COLLECTION_SAVE(26L),
  COLLECTION_DELETE(27L),
  COLLECTION_REFRESH(28L),
  COLLECTION_REFRESH_CURRENT(29L),
  COLLECTION_NOTES(30L),
  COLLECTION_CUR_NOTES(31L),
  COLLECTION_INITAUTOINSERT(32L),
  INLINE_SCRIPT(33L),
  COLLECTION_MAKECURRENT(34L),
  ACTIVEX_SCRIPT_METHOD(35L),
  CONDITIONAL_ACTION(36L),
  BINARY_DATA_ACTION(37L),
  ADD_AUDITLOG_ENTRY(38L),
  GOTO_URL(39L),
  PRINT_PREVIEW(40L),
  GOTO_EXPLORER_FOLDER(41L),
  INVOKE_WEB_SERVICE(42L),
  GENERATE_APP_EVENT(43L),
  UNUSED2(44L),
  INVOKE_USER_CONTROL(45L),
  COLLECTION_VALIDATE(46L),
  SEND_WEB_CONTAINER_MESSAGE(47L),
  NONE(-1L),
  ;
  private long numVal;

  FormEventHandlerResponseType(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
