package Mongoose.WinStudio.Enums;

public enum WSActions {
  NONE(0L),
  OPEN_FORM(1L),
  SAVE_DATA_METADATA(2L),
  SAVE_CLOSE_FORM(3L),
  CANCEL_CLOSE_FORM(4L),
  NEW_OBJECT_COLLECTION(5L),
  DELETE_OBJECT_COLLECTION(6L),
  REFRESH_COLLECTION(7L),
  REFRESH_CURRENT_RECORD(8L),
  FILTER_IN_PLACE(9L),
  FIRST_RECORD(10L),
  PREVIOUS_RECORD(11L),
  NEXT_RECORD(12L),
  LAST_RECORD(13L),
  FIND_FOR_CURRENT_FIELD(14L),
  ADD_FOR_CURRENT_FIELD(15L),
  DETAILS_CURRENT_FIELD(16L),
  NOTES(17L),
  VIEW_WROKFLOW(18L),
  HELP_CURRENT_FORM(19L),
  HELP(20L),
  DESIGNER(21L),
  REGENERATE_FORM(22L),
  UNDO_DESIGN_ACTION(23L),
  REDO_DESIGN_ACTION(24L),
  SPREADSHEET_COPY(25L),
  DOCS(26L),
  MORE_RECORDS(27L),
  ;
  private long numVal;

  WSActions(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
